core/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView

from core import settings
from dashboard import views as dash_views
from dashboard.sitemaps import PageSitemap

sitemaps = {
   'pages': PageSitemap,
}


urlpatterns = [
    url(r'^', include('landing_page.urls', namespace='landing_page')),

    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),

    url(r'^admin/', admin.site.urls),

    url(r'^login/$', dash_views.login, {'template_name': 'dashboard/login.html'}, name='login'),
    
    url(r'^logout/$', dash_views.logout, {'next_page': '/login/'}, name='logout'),

    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    url(r'^robots.txt$', dash_views.robot, name="robots_file"),

    url(r'^test/$', dash_views.hg_test, name='hg_test'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing_page/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^(?:(?P<slug>(privacy|terms|thanks|index-amp|privacy-amp|terms-amp))/)?$', views.index, name='index'),
]

templates/healthplansdirectsecure.com/base.html
{# landing page no. 04 #}

{% extends 'base.html' %}
{% load landing_page_tags %}


{% block meta %}
    {% include 'snippets/meta-default.html' %}
{% endblock meta %}


{% block title %}
    
    {% if page.get_page_name_display != 'Home' %}
    
        {% if page.title %} {{ page.title }}
        {% else %} {{ page.get_page_name_display }} {% endif %}
        
        {{ site_info.title_separator }}
    {% endif %}
    
        {{ page.get_page_title }}
    
{% endblock title %}


{% block css %}
    {% include 'snippets/css-link.html' %}
{% endblock css %}


{% block header %}
    <div class="top-nav">
        <div class="container">
            <div class="row">
                <div class="col">
                    <a href="{% url 'landing_page:index' %}" class="logo">
                        <img src="{% site_static 'img/logo.png' %}" alt="Logo"/>
                    </a>
    
                    <ul class="main-menu">
                        <li><a href="{% url 'landing_page:index' %}">Home</a></li>
                        <li><a href="{% url 'landing_page:index' 'privacy' %}">Privacy</a></li>
                        <li><a href="{% url 'landing_page:index' 'terms' %}">Terms</a></li>
                        <li><a href="#" class="seePlansJs">See Plans</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock header %}


{% block container %}{% endblock container %}


{% block footer %}
    <div class="footer">
        <div class="container">
            <div class="row">
                <div class="col">
                    <ul class="footer-ul">
                        <li>&copy; {{ request.get_host }}&nbsp;&nbsp;2017,&nbsp;&nbsp;All rights reserved.</li>
                        <li><a href="{% url 'landing_page:index' 'terms' %}">Terms &amp; Conditions</a></li>
                        <li><a href="{% url 'landing_page:index' 'privacy' %}">Privacy & Policy</a></li>
                        <li><a href="#homeJS" class="msScrollTo"><span class="fa fa-arrow-up"></span></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    {% include 'snippets/quote-form.html' %}
{% endblock footer %}


{% block js %}
    {% include 'snippets/scripts.html' %}
{% endblock js %}