core/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView

from core import settings
from dashboard import views as dash_views
from dashboard.sitemaps import PageSitemap

sitemaps = {
   'pages': PageSitemap,
}


urlpatterns = [
    url(r'^', include('landing_page.urls', namespace='landing_page')),

    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),

    url(r'^admin/', admin.site.urls),

    url(r'^login/$', dash_views.login, {'template_name': 'dashboard/login.html'}, name='login'),
    
    url(r'^logout/$', dash_views.logout, {'next_page': '/login/'}, name='logout'),

    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

    url(r'^robots.txt$', dash_views.robot, name="robots_file"),

    url(r'^test/$', dash_views.hg_test, name='hg_test'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.home, name='home'),

    url(r'^formInfo/$', views.site_form_list, name='form_list'),

    # url(r'^formInfo/add/$', views.site_form_list_create, name='form_data_add'),

    #url(r'^formInfo2/add/$', views.site2_form_list_create, name='form2_data_add'),

    # url(r'^(?P<domain>[a-z0-9\-.]+)/page/(?P<page_name>[a-z_]+)/(?P<page_item_type>[a-z_]+)/(?P<page_item_id>\d+)/AddFaqsFeatures/$',
    #     views.site2_form_list_create, name='form2_data_add'),

    url(r'^(?P<domain>[a-z0-9\-.]+)/$', views.site_settings, name='site_settings'),

    url(r'^(?P<domain>[a-z0-9\-.]+)/edit/$', views.edit_site_info, name='edit_site_info'),

    url(r'^(?P<domain>[a-z0-9\-.]+)/page/(?P<page_name>.*)/$',
        views.settings_page, name='settings_page'),

    url(r'^(?P<domain>[a-z0-9\-.]+)/page/(?P<page_name>.*)/edit/$',
        views.edit_page, name='edit_page'),

    url(r'^(?P<domain>[a-z0-9\-.]+)/page/(?P<page_name>.*)/(?P<page_item_type>.*)/(?P<page_item_id>\d+)/edit/$',
        views.edit_page_item, name='edit_page_item'),

    url(r'^(?P<domain>[a-z0-9\-.]+)/page/(?P<page_name>.*)/(?P<page_item_type>.*)/(?P<page_item_id>\d+)/AddFaqsFeatures/$',
        views.site2_form_list_create, name='form2_data_add'),

    url(r'^(?P<domain>[a-z0-9\-.]+)/template(?:/(?P<app_label>.*))?(?:/(?P<page_name>[a-z\-]+))?/$',
        views.templates, name='template'),

    url(r'^(?P<domain>[a-z0-9\-.]+)/staticfiles(?:/(?P<app_label>.*))?(?:/(?P<file_name>[a-z.\-]+))?/$',
        views.static_files, name='static_files'),

    # url(r'^(?P<domain>[a-z0-9\-.]+)/(?P<app_label>[a-z_]+)/(?P<model_name>[a-z]+)(?:/(?P<action>add))?/$',
    #     views.site_settings_items, name='site_settings_items'),
    #
    # url(r'^(?P<domain>[a-z0-9\-.]+)/(?P<app_label>[a-z_]+)/(?P<model_name>[a-z]+)/(?P<pk>\d+)/(?P<action>change)/$',
    #     views.site_settings_items, name='site_settings_items'),
    #url(r'^show/$', views.show,name='show'),
    url(r'^(?P<domain>[a-z0-9\-.]+)/page/(?P<page_name>.*)/available/$',
        views.available, name='available'),

    url(r'^(?P<domain>[a-z0-9\-.]+)/page/(?P<page_name>.*)/available/show/$',
        views.show, name='show'),

    url(r'^tinymceupload/$', views.tinymce_upload, name='writing-fileupload'),

]

dashboard/models.py
# -*- coding: utf-8 -*-
from __future__ import print_function, unicode_literals

from django.db import models
from django.conf import settings
from django.utils import timezone
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.contrib.sites.models import Site
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.auth.models import BaseUserManager, PermissionsMixin, AbstractBaseUser


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given username, email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


@python_2_unicode_compatible
class User(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(
        verbose_name=_('Email Address'),
        max_length=255,
        unique=True,
    )

    first_name = models.CharField(
        verbose_name=_('First Name'),
        max_length=50,
        blank=True
    )

    last_name = models.CharField(
        verbose_name=_('Last Name'),
        max_length=50,
        blank=True
    )

    is_staff = models.BooleanField(
        verbose_name=_('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )

    is_active = models.BooleanField(
        verbose_name=_('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )

    date_joined = models.DateTimeField(
        _('date joined'),
        default=timezone.now
    )

    created_by = models.ForeignKey(
        'self',
        blank=True, null=True,
        on_delete=models.SET_NULL
    )

    hg_username = models.CharField(
        max_length=200,
        blank=True,
        null=True
    )

    hg_email = models.EmailField(
        blank=True,
        null=True
    )

    hg_full_name = models.CharField(
        max_length=200,
        blank=True,
        null=True
    )

    objects = UserManager()

    USERNAME_FIELD = 'email'

    class Meta:
        db_table = 'user'
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __str__(self):
        return self.email

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Returns the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def group_name(self):
        return ','.join([group.name for group in self.groups.all()])

    def is_site_admin(self):
        if self.groups.filter(name=settings.GROUP_ADMIN).exists():
            return True
        return False

    def is_admin(self):
        return self.is_superuser or self.is_site_admin()
    is_admin.boolean = True

    def is_editor(self):
        if self.groups.filter(name=settings.GROUP_EDITOR).exists():
            return True
        return False


class SiteInfo(models.Model):

    site = models.ForeignKey(
        Site,
        on_delete=models.CASCADE,
        unique=True
    )

    site_meta_webmaster = models.TextField(
        blank=True, null=True
    )

    site_analytics_js = models.TextField(
        blank=True, null=True
    )

    # required
    site_title = models.TextField(
        blank=True, null=True
    )

    title_separator = models.CharField(
        max_length=10,
        choices=(
            ('|', '|'),
            ('-', '-')
        ),
        default='|'
    )

    # required
    phone_number = models.CharField(
        max_length=20,
        blank=True, null=True
    )

    email_id = models.EmailField(
        blank=True, null=True
    )

    # required
    main_heading = models.TextField(
        blank=True, null=True
    )

    # required
    main_heading_sub = models.TextField(
        blank=True, null=True
    )

    created = models.DateTimeField(
        auto_now_add=True
    )

    # for keeping record of last edited date
    date_edited = models.DateTimeField(
        auto_now=True
    )

    # only django admin can change this field
    published = models.BooleanField(
        default=True
    )

    class Meta:
        verbose_name = 'Site Info'
        ordering = ['site__id']

    def __str__(self):
        return "SiteInfo({0})".format(self.site.domain)


class Page(models.Model):

    site_info = models.ForeignKey(
        SiteInfo,
        on_delete=models.CASCADE
    )

    # priority field must be added
    # in recent future for sitemap
    # index - 1.0, privacy - 0.8, terms - 0.8
    page_name = models.CharField(
        max_length=100,
        choices=(
            ('index', 'Home'),
            ('privacy', 'Privacy'),
            ('terms', 'Terms'),
            ('thanks', 'Thanks'),
            ('index-amp', 'Home-amp'),
            ('privacy-amp', 'Privacy-amp'),
            ('terms-amp', 'Terms-amp'),
        )
    )

    page_nav_name = models.CharField(
        max_length=500,
        blank=True, null=True
    )

    # page_type is related to django app - app_label
    page_type = models.CharField(
        max_length=100,
        choices=settings.SITE_REGISTERED_APP_LABELS,
        default='landing_page'
    )

    # be default this must be populated by SiteInfo site_title
    title = models.TextField(
        blank=True,  # this is not using in website
        null=True
    )

    # not required for index
    sub_title = models.TextField(
        blank=True,
        null=True
    )

    # must be unique for every page
    meta_description = models.TextField(
        blank=True, null=True
    )

    # comma separated meta keywords
    meta_keywords = models.TextField(
        blank=True, null=True
    )

    published = models.BooleanField(
        default=True
    )

    date_published = models.DateTimeField(
        blank=True, null=True
    )

    created = models.DateTimeField(
        auto_now_add=True
    )

    date_edited = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        unique_together = ('site_info', 'page_name')
        ordering = ['site_info__site__id', 'page_name']

    def __str__(self):
        return "{0} - {1}".format(self.site_info.site.domain, self.page_name)

    def get_page_title(self):
        if self.sub_title:
            return "{0} {1} {2}".format(self.sub_title, self.site_info.title_separator, self.site_info.site_title)
        return self.site_info.site_title

    def get_page_nav_name(self):
        return self.page_nav_name or self.get_page_name_display()

    def get_absolute_url(self):
        args = [] if self.page_name == 'index' else [self.page_name]
        return reverse('{0}:index'.format(self.page_type),
                       args=args)


class AbstractItem(models.Model):

    PAGE_ITEM = True

    instance_name = models.CharField(
        max_length=100,
        unique=True
    )

    published = models.BooleanField(
        default=True
    )

    date_published = models.DateTimeField(
        blank=True, null=True
    )

    created = models.DateTimeField(
        auto_now_add=True
    )

    # for logging
    date_edited = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        abstract = True


class PageItem(models.Model):

    page = models.ForeignKey(
        Page,
        on_delete=models.CASCADE
    )

    content_type = models.ForeignKey(
        ContentType,
        on_delete=models.CASCADE
    )

    object_id = models.PositiveIntegerField()

    content_object = GenericForeignKey(
        'content_type', 'object_id'
    )

    configuration = models.TextField(
        blank=True, null=True
    )

    created = models.DateTimeField(
        auto_now_add=True
    )

    date_edited = models.DateTimeField(
        auto_now=True
    )

    # class Meta:
    #     unique_together = ('page', 'object_id')

    def __str__(self):
        return '{0} - {1} - {2} - {3}'.format(self.page.site_info.site.domain, self.page.page_name,
                                              self.content_type.model, self.content_object.instance_name)



class SiteFormDataModel(models.Model):

    domain_name = models.CharField(
        max_length=150
    )

    zip_code = models.CharField(
        max_length=5,
        db_index=True
    )

    state = models.CharField(
        max_length=100,
        blank=True, null=True
    )

    dob = models.DateField(

dashboard/templates/dashboard/available_items.html
{% extends 'dashboard/base.html' %}

{% block title %}Add item to page | {{ block.super }}{% endblock title %}

{% block header %}
    
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{% url 'dashboard:home' %}">Dashboard</a>
        </li>
        <li class="breadcrumb-item">
            <a href="{% url 'dashboard:site_settings' domain %}">{{ domain }}</a>
        </li>
        <li class="breadcrumb-item active">
            {{ pagename }}
        </li>
    </ol>

{% endblock header %}


{% block container %}
    
    <div class="container">
        <div class="col-sm-12">
            <form action="{% url 'dashboard:show' domain pagename %}" method="post">
                {% csrf_token %}
                
                {% for key, value in allItems.items %}
                    <div class="form-group">
                        <label class="custom-control custom-checkbox mb-2 mr-sm-2 mb-sm-0">
                            <input type="checkbox" class="custom-control-input" name="{{ key }}" value={{ value }}
                                   id="{{ key }}"
                                    {% if key in is_present.keys %} checked {% endif %}>
                            <span class="custom-control-indicator"></span>
                            <span class="custom-control-description">{{ key|title }}</span>
                        </label>
                    </div>
                {% endfor %}
                
                <button type="submit" class="btn btn-primary">Update</button>
            </form>
        </div>
    </div>
    
{% endblock %}

dashboard/templates/dashboard/base.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link type="text/css" rel="stylesheet" href="{% static 'dashboard/css/bootstrap.min.css' %}">
<style type="text/css">
    .btn{cursor: pointer}
    .smooth-border-radius .card:not(:last-child) {
        border-bottom-left-radius: 0;
        border-bottom-right-radius: 0;
    }
    .smooth-border-radius .card:not(:first-child) {
        border-top-left-radius: 0;
        border-top-right-radius: 0;
    }
    .header-right{
        position: absolute;
        top: 7px;
        right: 7px;
    }
    .header-right .btn{
        padding: .3rem .5rem;
    }
    label[for^="feat_img_upload"]{
        font-size: 15px;
        margin-bottom: 0;
    }
    textarea.form-control{height: 250px}
    textarea.form-control {padding: 12px 20px}
</style>
{% endblock css %}

{% block extra_css %}{% endblock extra_css %}

{% block title %}Site Management{% endblock title %}

{% block header %}{% endblock header %}

{% block extra_header %}
<div class="header-right">
    <a href="{% url 'logout' %}" class="btn btn-danger">Logout</a>
</div>
{% endblock extra_header %}

{% block container %}{% endblock container %}
{% block footer %}{% endblock footer %}


{% block js %}
<script type="text/javascript" src="{% static 'dashboard/js/jquery-3.2.1.slim.min.js' %}"></script>
<script type="text/javascript" src="{% static 'dashboard/js/popper.min.js' %}"></script>
<script type="text/javascript" src="{% static 'dashboard/js/bootstrap.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js"></script>
{#{% include 'snippets/tinymce.html' %}#}
{% endblock js %}

{% block extra_js %}{% endblock extra_js %}

dashboard/templates/dashboard/edit_faq_n_feat.html
{% extends 'dashboard/base.html' %}

{% load static %}

{% block title %} {{ itemtype }} | {{ block.super }}{% endblock title %}

{% block extra_css %}
    <style>
    .cancel-faq {
        width: 38px;
        padding: 6px
    }
    .cancel-faq span{
        cursor: pointer;
        background: #eee;
        border: 1px solid #333;
        padding: 2.5px 9px;
        border-radius: 50%;
    }
    #plz-update {
        font-size: 20px;
        font-weight: bold;
        color: red;
        display: none;
        -webkit-animation: pulse 1s linear infinite;
        -moz-animation: pulse 1s linear infinite;
        animation: pulse 1s linear infinite;
    }
    @keyframes pulse {
        50% {
            opacity: 0;
        }
    }
    </style>
{% endblock %}

{% block header %}
    
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{% url 'dashboard:home' %}">Dashboard</a>
        </li>
        <li class="breadcrumb-item">
            <a href="{% url 'dashboard:site_settings' domain %}">{{ site.domain }}</a>
        </li>
        <li class="breadcrumb-item">
            <a href="{% url 'dashboard:site_settings' domain %}">{{ pageitem.page.page_name }}</a>
        </li>
        <li class="breadcrumb-item active">Edit {{ itemtype|title }}</li>

</ol>

{% endblock header %}

{% block container %}

    <div class="container">
        
        <div class="col-sm-12">
            <h2>Edit content for {{ pageitem.content_type.model }}:
            <a
                target="_blank"
                class="float-right"
                href="{{ request.scheme }}://{{ site.domain }}{% if pagename != "index" %}/{{ pagename }}{% endif %}"
            >View page</a>
        </h2>
            
            <form class="form" method="post" id="dataform" enctype="multipart/form-data">
                
                {% csrf_token %}
                
                <div id="form_wrapper">
                
                {% for key,val in mainContent.items %}
                    <div class="form-row" data-dict_indicator="{{ key }}">
                        <div class="form-group col-md-6 faq_ques">
                            <div class="input-group">
                                <span class="input-group-addon" id="{{ itemtype }}_q_0">Q</span>
                                <input
                                        type="text"
                                        name="{{ itemtype }}_q_0"
                                        class="form-control"
                                        placeholder="{{ content1 }}"
                                        aria-label="{{ content1 }}"
                                        value="{{ val.Question }}{{ val.Heading }}" {# if question or heading #}
                                        aria-describedby="{{ itemtype }}_q_0">
                            </div>
                        </div>
                        
                        <div class="form-group col-md-6 faq_ans">
                            <div class="input-group">
                                <span class="input-group-addon" id="{{ itemtype }}_a_0">A</span>
                                <input
                                        type="text"
                                        name="{{ itemtype }}_a_0"
                                        class="form-control"
                                        placeholder="{{ content2 }}"
                                        aria-label="{{ content2 }}"
                                        value="{{ val.Answer }}{{ val.Content }}"   {# if answer or content #}
                                        aria-describedby="{{ itemtype }}_a_0">
                                 <div class="cancel-faq text-center"><span>x</span></div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                
                </div>
                
                <button class="btn btn-outline-warning add-new">
                    {% if itemtype == 'faq' %}
                        Add new Q/A
                    {% else %}
                        Add new features
                    {% endif %}
                </button>
                <button type="submit" class="btn btn-success">Update</button>
                <span id="plz-update">&#8592;Some Data may lost, please update first</span>
            
            </form>
            
            {# <div id="json"></div>#}
            
        </div>
    
    </div>
{% endblock container %}

{% block extra_js %}
<script type="text/javascript">

    $(document).ready(function(){

        function DeleteItem() {
            $('.cancel-faq').unbind().click(function (e) {
                e.preventDefault();
                var _elem = $(this).closest('.form-row');
                _elem.remove();
                $('#plz-update').show();
            });
        }

        DeleteItem();

        $('.add-new').click(function (e) {
            e.preventDefault();
            var _count = $('#form_wrapper .form-row').length;
            var _html =
                '<div class="form-row" data-dict_indicator="item_'+_count+'">' +
                    '<div class="form-group col-md-6 faq_ques">' +
                        '<div class="input-group">' +
                            '<span class="input-group-addon" id="{{ itemtype }}_q_' + _count + '">Q</span>' +
                            '<input ' +
                                    'type="text"' +
                                    'name="{{ itemtype }}_q_' + _count + '"' +
                                    'class="form-control"' +
                                    'placeholder="{{ content1 }}"' +
                                    'aria-label="{{ content1 }}"' +
                                    'aria-describedby="{{ itemtype }}_q_' + _count + '">' +
                        '</div>' +
                    '</div>' +

                    '<div class="form-group col-md-6 faq_ans">' +
                        '<div class="input-group">' +
                            '<span class="input-group-addon" id="{{ itemtype }}_a_' + _count + '">A</span>' +
                            '<input ' +
                                    'type="text"' +
                                    'name="{{ itemtype }}_a_' + _count + '"' +
                                    'class="form-control"' +
                                    'placeholder="{{ content2 }}"' +
                                    'aria-label="{{ content2 }}"' +
                                    'aria-describedby="{{ itemtype }}_a_' + _count + '">' +
                            '<div class="cancel-faq text-center"><span>x</span></div>' +
                        '</div>' +
                    '</div>' +
                '</div>';
            if(_count < 8)  //question answer limited to 8
                $('#form_wrapper').append(_html);

            DeleteItem();
        });




        var _json_data = {};
        var c = 0;  //counter
        $('#dataform').submit(function (e) {
            e.preventDefault();
            $('#form_wrapper .form-row').each(function () {
                var _t = $(this);
                if(_t.find('input[aria-describedby^="{{ itemtype }}_q_"]').val()) {
                    var que_ans = {
                        "{{ content1 }}": _t.find('input[aria-describedby^="{{ itemtype }}_q_"]').val(),
                        "{{ content2 }}": _t.find('input[aria-describedby^="{{ itemtype }}_a_"]').val()
                    };
                    if(_t.attr('data-dict_indicator'))  {# if renders from backend data #}
                        _json_data[_t.attr('data-dict_indicator')] = que_ans
                    else
                        _json_data["item_" + c] = que_ans;
                    c++;
                }
            });
            _json_data = JSON.stringify(_json_data);

            $.ajax({
                type        : 'POST', // define the type of HTTP verb we want to use (POST for our form)
                url         : '{% url 'dashboard:form2_data_add' domain pageitem.page.page_name pageitem.content_type.model pageitem.id %}', // the url where we want to POST
                data        : _json_data,
                beforeSend  : function(xhr) {xhr.setRequestHeader("X-CSRFToken", $.cookie('csrftoken'));},
                dataType    : 'json', // what type of data do we expect back from the server
                encode      : true ,
                success     : function (data) {
                                window.location = "{{ request.scheme }}://{{ request.get_host }}{% url 'dashboard:site_settings' domain %}"
                          },
                error: function(jqXHR, textStatus, errorThrown){
                    //if fails
                }
            });

            //$('#json').html(_json_data);
        });


    });
</script>
{% endblock %}

dashboard/templates/dashboard/edit_page_info.html
{% extends 'dashboard/base.html' %}

{% block header %}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="{% url 'dashboard:home' %}">Dashboard</a>
    </li>
    <li class="breadcrumb-item">
        <a href="{% url 'dashboard:site_settings' domain %}">{{ site.domain }}</a>
    </li>
    <li class="breadcrumb-item active">Edit Page Info</li>

</ol>

{% endblock header %}

{% block container %}

<div class="container">

    <div class="col-sm-12">
        
        <h2>Edit basic settings:
            <a
                target="_blank"
                class="float-right"
                {# pagename not in the context (dashboard->views->edit_page) #}
                href="{{ request.scheme }}://{{ site.domain }}{% if pagename != "index" %}/{{ pagename }}{% endif %}"
            >View page</a>
        </h2>

        <form class="form" method="post">

            {% csrf_token %}

            <div class="form-group">
                <label for="id_page_nav_name">Page Nav Name:</label>
                <input class="form-control" name="page_nav_name" value="{{ form.page_nav_name.value|default:'' }}" id="id_page_nav_name"/>
            </div>

            <div class="form-group">
                <label for="id_title">Page Title:</label>
                <input class="form-control" name="title" value="{{ form.title.value|default:'' }}" id="id_title">
            </div>

            <div class="form-group d-none"> {# not displaying #}
                <label for="id_sub_title">Page Sub-Title:</label>
                <input class="form-control" name="sub_title" value="{{ form.sub_title.value|default:'' }}" id="id_sub_title"/>
            </div>



            <div class="form-group">
                <label for="id_meta_description">Page Meta Description:</label>
                <textarea class="form-control" rows="2" name="meta_description" cols="40" rows="10" id="id_meta_description">{{ form.meta_description.value|default:'' }}</textarea>
            </div>

            <div class="form-group">
                <label for="id_meta_keywords">Page Meta Keyword:</label>
                <textarea
                        class="form-control"
                        name="meta_keywords"
                        placeholder="Comma(,) separated value"
                        id="id_meta_keywords"
                >{{ form.meta_keywords.value|default:'' }}</textarea>
            </div>

            <button type="submit" class="btn btn-primary">Update</button>

        </form>

    </div>

</div>
{% endblock container %}

dashboard/templates/dashboard/edit_site_info.html
{% extends 'dashboard/base.html' %}

{% block header %}

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="{% url 'dashboard:home' %}">Dashboard</a>
    </li>
    <li class="breadcrumb-item">
        <a href="{% url 'dashboard:site_settings' domain %}">{{ site.domain }}</a>
    </li>
    <li class="breadcrumb-item active">Edit Site Info</li>

</ol>

{% endblock header %}

{% block container %}

<div class="container">

    <div class="col-sm-12">
        
        <h2>Edit basic settings:
            <a
                target="_blank"
                class="float-right"
                href="{{ request.scheme }}://{{ site.domain }}"
            >View page</a>
        </h2>

        <form class="form" method="post">

            {% csrf_token %}

            <div class="form-group">
                <label for="id_site_title">Site title:</label>
                <input class="form-control" name="site_title" value="{{ form.site_title.value|default:'' }}" id="id_site_title"/>
            </div>

            <div class="form-group">
                <label for="id_phone_number">Phone number:</label>
                <input type="text" class="form-control" name="phone_number" value="{{ form.phone_number.value|default:'' }}" maxlength="20" id="id_phone_number" />
            </div>

            <div class="form-group">
                <label for="id_email_id">Email id:</label>
                <input type="email" class="form-control" name="email_id" value="{{ form.email_id.value|default:'' }}" maxlength="254" id="id_email_id" />
            </div>

            <div class="form-group">
                <label for="id_main_heading">Main heading:</label>
                <textarea class="form-control" name="main_heading" id="id_main_heading">{{ form.main_heading.value|default:'' }}</textarea>
            </div>

            <div class="form-group">
                <label for="id_main_heading_sub">Main heading sub:</label>
                <textarea class="form-control" name="main_heading_sub" id="id_main_heading_sub">{{ form.main_heading_sub.value|default:'' }}</textarea>
            </div>

            <div class="form-group">
                <label for="id_site_meta_webmaster">Site Meta Webmaster:</label>
                <textarea class="form-control" name="site_meta_webmaster" id="id_site_meta_webmaster">{{ form.site_meta_webmaster.value|default:'' }}</textarea>
            </div>

            <div class="form-group">
                <label for="id_site_analytics_js">Site Analytic JS:</label>
                <textarea class="form-control" name="site_analytics_js" id="id_site_analytics_js">{{ form.site_analytics_js.value|default:'' }}</textarea>
            </div>

            <button type="submit" class="btn btn-primary">Update</button>

        </form>

    </div>

</div>
{% endblock container %}

dashboard/templates/dashboard/show.html
{% for i,q in items.items %}

{{ i }}:{{ q }}<br>

{% endfor %}